{"name": "人脸信息管理--删除功能", "status": "skipped", "statusDetails": {"message": "Skipped: 普利人脸服务连接目前不可用", "trace": "('TestCases\\\\Test3_FaceRecognition\\\\test_1_face_info_manage.py', 67, 'Skipped: 普利人脸服务连接目前不可用')"}, "parameters": [{"name": "data", "value": "{'case_id': 2, 'sheet_name': 'face_info_delete', 'title': '正常删除', 'delete_face_info': '系统管理员'}"}], "start": 1607074566272, "stop": 1607074566272, "uuid": "5ea70c29-2355-4c68-ae0b-22725f725fcc", "historyId": "d8eeae30b97b10a460066b653c566f65", "testCaseId": "8e4831cbc3a9e609e5647af967dbfdfe", "fullName": "TestCases.Test3_FaceRecognition.test_1_face_info_manage.TestFaceRecognition#test_delete_face_info", "labels": [{"name": "feature", "value": "人脸识别"}, {"name": "epic", "value": "项目名称：中控平台V2.1"}, {"name": "story", "value": "人脸信息管理"}, {"name": "tag", "value": "@pytest.mark.skip(reason='普利人脸服务连接目前不可用')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases.Test3_FaceRecognition"}, {"name": "suite", "value": "test_1_face_info_manage"}, {"name": "subSuite", "value": "TestFaceRecognition"}, {"name": "host", "value": "DESKTOP-901EL0R"}, {"name": "thread", "value": "9616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.Test3_FaceRecognition.test_1_face_info_manage"}]}