{"name": "人脸信息管理--访客新增功能", "status": "skipped", "statusDetails": {"message": "Skipped: 普利人脸服务连接目前不可用", "trace": "('TestCases\\\\Test3_FaceRecognition\\\\test_1_face_info_manage.py', 19, 'Skipped: 普利人脸服务连接目前不可用')"}, "parameters": [{"name": "data", "value": "{'case_id': 2, 'sheet_name': 'face_info_add', 'title': '正常添加', 'add_type': '员工添加', 'name': None, 'employee': '系统管理员', 'gender': '女', 'telephone_number': None, 'id_card_number': '421023199902012102', 'company': None, 'dirpath': 'C:\\\\Users\\\\yyzz\\\\Desktop\\\\图片\\\\face\\\\customer_modify', 'smartwatch': '新增-智能手表001'}"}], "start": 1607074566244, "stop": 1607074566244, "uuid": "a20a54d6-dad3-4bad-bb8f-5adad9e92369", "historyId": "307b6fca41a9342572ed2bde4d5b2c15", "testCaseId": "7166cff1e398816233ddd0b212ad9a79", "fullName": "TestCases.Test3_FaceRecognition.test_1_face_info_manage.TestFaceRecognition#test_add_face_info", "labels": [{"name": "feature", "value": "人脸识别"}, {"name": "epic", "value": "项目名称：中控平台V2.1"}, {"name": "story", "value": "人脸信息管理"}, {"name": "tag", "value": "@pytest.mark.skip(reason='普利人脸服务连接目前不可用')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases.Test3_FaceRecognition"}, {"name": "suite", "value": "test_1_face_info_manage"}, {"name": "subSuite", "value": "TestFaceRecognition"}, {"name": "host", "value": "DESKTOP-901EL0R"}, {"name": "thread", "value": "9616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.Test3_FaceRecognition.test_1_face_info_manage"}]}