{"name": "人脸信息管理--访客新增功能", "status": "skipped", "statusDetails": {"message": "Skipped: 普利人脸服务连接目前不可用", "trace": "('TestCases\\\\Test3_FaceRecognition\\\\test_1_face_info_manage.py', 19, 'Skipped: 普利人脸服务连接目前不可用')"}, "parameters": [{"name": "data", "value": "{'case_id': 1, 'sheet_name': 'face_info_add', 'title': '正常添加', 'add_type': '访客添加', 'name': '新增的访客001', 'employee': None, 'gender': '男', 'telephone_number': 15973177566, 'id_card_number': None, 'company': '武汉精伦电气有限公司', 'dirpath': 'C:\\\\Users\\\\yyzz\\\\Desktop\\\\图片\\\\face\\\\customer_add', 'smartwatch': '新增-智能手表001'}"}], "start": 1607074566229, "stop": 1607074566229, "uuid": "5fbf6170-5ff5-4d9e-9118-714a2c04863b", "historyId": "eed24345e834a7b94bf76f92fec0254b", "testCaseId": "7166cff1e398816233ddd0b212ad9a79", "fullName": "TestCases.Test3_FaceRecognition.test_1_face_info_manage.TestFaceRecognition#test_add_face_info", "labels": [{"name": "feature", "value": "人脸识别"}, {"name": "epic", "value": "项目名称：中控平台V2.1"}, {"name": "story", "value": "人脸信息管理"}, {"name": "tag", "value": "@pytest.mark.skip(reason='普利人脸服务连接目前不可用')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases.Test3_FaceRecognition"}, {"name": "suite", "value": "test_1_face_info_manage"}, {"name": "subSuite", "value": "TestFaceRecognition"}, {"name": "host", "value": "DESKTOP-901EL0R"}, {"name": "thread", "value": "9616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.Test3_FaceRecognition.test_1_face_info_manage"}]}